openapi: 3.0.0
info:
  title: Construction v2
  version: 1.0.0
servers:
  - url: http://138.197.141.19:4000/api
tags:
  - name: Auth
  - name: Company
  - name: Project
  - name: Task
  - name: Users
  - name: Work Log Service
  - name: Invoices

components:
  securitySchemes:
    BearerAuth:
      type: apiKey
      in: header
      name: Authorization
      description: "Bearer token for authentication"
   
security:
      - BearerAuth: [] 

paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: iamshivagyawali@gmail.com
                password: shiva@123
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /companies/register:
    post:
      tags:
        - Company
      summary: Create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                companyName: Shiva & Co.
                companyEmail: shiva@gmail.com
                name: Shiva Gyawali
                email: shiva@gmail.com
                password: shiva@123
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /projects/list:
    get:
      tags:
        - Project
      summary: Retrieve all Projects
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /projects/{id}:
    get:
      tags:
        - Project
      summary: Get One Project
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 75056021-9a86-4df2-8d4b-3bcfb699c0ee
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - Project
      summary: Update Project
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: 'Second Project By Shiva & Co Updated'
                description: A new project description by Second and Co
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Project
      summary: Delete Project
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /projects/create:
    post:
      tags:
        - Project
      summary: Create Project
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: 'First Project By Ashish & Co'
                description: A new project description by First and Co
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /tasks/list:
    get:
      tags:
        - Task
      summary: Retrieve all Tasks
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /tasks/create:
    post:
      tags:
        - Task
      summary: Create Task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: New Task Example
                description: This is a detailed description of the task.
                projectId: 5c872fed-bef2-4943-9c4c-fe978d0d1e95
                userIds:
                  - 3a3b7f74-4bf7-4980-9698-46fc61f9cf0f
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /tasks/{id}:
    put:
      tags:
        - Task
      summary: Update Task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: New Task Example
                description: This is a detailed description of the task.
                projectId: 75056021-9a86-4df2-8d4b-3bcfb699c0ee
                userIds:
                  - 3a3b7f74-4bf7-4980-9698-46fc61f9cf0f
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Task
      summary: Delete Task
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /users/list:
    get:
      tags:
        - Users
      summary: Retrieve all Users
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /users/create:
    post:
      tags:
        - Users
      summary: Create User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: shiva1@gmail.com
                name: Shiva Gyawali
                role: worker
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /worklogs/list:
    get:
      tags:
        - Work Log Service
      summary: Retrieve all My Logs
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /worklogs/start:
    post:
      tags:
        - Work Log Service
      summary: Create Log
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                latitude: '27.6588'
                longitude: '83.5710'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /worklogs/end:
    post:
      tags:
        - Work Log Service
      summary: Stop Work Logs
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                latitude: '27.6588'
                longitude: '83.5710'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /invoices/list:
    get:
      tags:
        - Invoices
      summary: Retrieve all Invoices
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /invoices/create:
    post:
      tags:
        - Invoices
      summary: Create Invoice
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                startDate: '2025-03-12'
                endDate: '2025-03-12'
                userId: 44e36b22-87ec-4127-9b9c-734bac2eeaa7
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /invoices/{invoiceId}/pay:
    put:
      tags:
        - Invoices
      summary: Pay Invoice
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                startDate: '2025-03-12'
                endDate: '2025-03-12'
                userId: 44e36b22-87ec-4127-9b9c-734bac2eeaa7
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
